### ISSUE TITLE
itemReviewed and review body have been not found!

### ISSUE THREAD

**Issue by shinesoftware** [mageplaza/magento-2-seo#101]
Hello guys,

we have noticed that the attribute itemReviewed is not handled in your extension.

Look at this example:

    <html>
    <head>
        <title>Legal Seafood</title>
        <script type="application/ld+json">
        {
        "@context": "https://schema.org/",
        "@type": "AggregateRating",
        "itemReviewed": {
            "@type": "Restaurant",
            "image": "http://www.example.com/seafood-restaurant.jpg",
            "name": "Legal Seafood",
            "servesCuisine": "Seafood",
            "telephone": "1234567",
            "address" : {
            "@type": "PostalAddress",
            "streetAddress": "123 William St",
            "addressLocality": "New York",
            "addressRegion": "NY",
            "postalCode": "10038",
            "addressCountry": "US"
            }
        },
        "ratingValue": "88",
        "bestRating": "100",
        "ratingCount": "20"
        }
        </script>
    </head>
    <body>
    </body>
    </html>

furthermore the content of the review is not handled too. Look at:

    <html>
    <head>
        <title>The Catcher in the Rye</title>
        <script type="application/ld+json">
        {
        "@context": "https://schema.org/",
        "@type": "Product",
        "brand": {
            "@type": "Brand",
            "name": "Penguin Books"
        },
        "description": "The Catcher in the Rye is a classic coming-of-age story: an story of teenage alienation, capturing the human need for connection and the bewildering sense of loss as we leave childhood behind.",
        "sku": "9780241984758",
        "mpn": "925872",
        "image": "http://www.example.com/catcher-in-the-rye-book-cover.jpg",
        "name": "The Catcher in the Rye",
        "review": {
            "@type": "Review",
            "reviewRating": {
            "@type": "Rating",
            "ratingValue": "5"
            },
            "author": {
            "@type": "Person",
            "name": "John Doe"
            },
            "reviewBody": "I really enjoyed this book. It captures the essential challenge people face as they try make sense of their lives and grow to adulthood."
        },
        "aggregateRating": {
            "@type": "AggregateRating",
            "ratingValue": "88",
            "bestRating": "100",
            "ratingCount": "20"
        },
        "offers": {
            "@type": "Offer",
            "url": "https://example.com/offers/catcher-in-the-rye",
            "priceCurrency": "USD",
            "price": "5.99",
            "priceValidUntil": "2020-11-05",
            "itemCondition": "https://schema.org/UsedCondition",
            "availability": "https://schema.org/InStock",
            "seller": {
            "@type": "Organization",
            "name": "eBay"
            }
        }
        }
        </script>
    </head>
    <body>
    </body>
    </html>

Regards

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza.
The 'itemReviewed' and 'reviewBody' field are fields for type Review not for type Product.
You can read this instruction to get more detail:

- https://developers.google.com/search/docs/data-types/review-snippet

- https://developers.google.com/search/docs/data-types/product

**Comment by giaphn** [comment]
Closed due no response within 7 days.
