### ISSUE TITLE
Product schema images have /pub/ hardcoded in URL.

### ISSUE THREAD

**Issue by jasuten** [mageplaza/magento-2-seo#103]
Product schema images have /pub/ hardcoded in URL, this will generate an invalid url on websites that set the base directory to the pub folder (which is best practice anyway).

https://github.com/mageplaza/magento-2-seo/blob/0b930f0f78d0bc936654398d54a330c101dc3685/Plugin/SeoRender.php#L387

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza.

To solve your problem, please download and replace this file:

- app\code\Mageplaza\Seo\Plugin\SeoRender.php
[SeoRender.zip](https://github.com/mageplaza/magento-2-seo/files/6168356/SeoRender.zip)

Then clear the cache and check again

**Comment by giaphn** [comment]
Closed due no response within 7 days.
