### ISSUE TITLE
proxy_fcgi:error

### ISSUE THREAD

**Issue by zapateroremendon** [mageplaza/magento-2-seo#105]
### Preconditions (*)

1. Magento 2.3.6-p1
2. php-fpm73
3. Varnish 6
4. Centos 8
5. Porto theme 2.3.5

### Steps to reproduce (*)

1. install Mageplaza Seo Ultimate 4.1.0

### Expected result (*)

1. page loading without issue

### Actual result (*)

1. Broken internal javascripts and css files
2. apache error logs:
[Sun May 02 21:42:07.362116 2021] [proxy_fcgi:error] [pid 1002977:tid 139660240017152] [client xxxxx:33226] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getValue() on bool in /home/user/public_html/app/code/Mageplaza/Seo/Plugin/SeoRender.php:739\nStack trace:\n#0 /home/user/public_html/app/code/Mageplaza/Seo/Plugin/SeoRender.php(846): Mageplaza\\Seo\\Plugin\\SeoRender->getConfigurableProductStructuredData(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#1 /home/user/public_html/app/code/Mageplaza/Seo/Plugin/SeoRender.php(446): Mageplaza\\Seo\\Plugin\\SeoRender->addProductStructuredDataByType('configurable', Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#2 /home/user/public_html/app/code/Mageplaza/Seo/Plugin/SeoRender.php(263): Mageplaza\\Seo\\Plugin\\SeoRender->showProductStructuredData()\n#3 /home/user/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Mageplaza\\Seo\\Plugin\\SeoRender->afterRenderHeadContent(Object(Magento\\Framework\\View\\Page\\Config\\Renderer\\Interceptor), '<meta charset="...')\n#4 /home/user/public_html/ven...'

webpage is https://www.calzadosyoyito.cl

Thanks for helping us

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza.
Please download and replace this file:
[SeoRender.zip](https://github.com/mageplaza/magento-2-seo/files/6425518/SeoRender.zip)

Then clear the cache and check the result.
Thank you!

**Comment by zapateroremendon** [comment]
Hi Shox, 
Thanks for your answer, however still experience issue on it, error now says:
[Wed May 05 12:29:03.718796 2021] [proxy_fcgi:error] [pid 155654:tid 139682988795648] [client xxx:33044] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getValue() on bool in /home/user/public_html/app/code/Mageplaza/Seo/Plugin/SeoRender.php:702\nStack trace:\n#0 /home/user/public_html/app/code/Mageplaza/Seo/Plugin/SeoRender.php(804): Mageplaza\\Seo\\Plugin\\SeoRender->getConfigurableProductStructuredData(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#1 /home/user/public_html/app/code/Mageplaza/Seo/Plugin/SeoRender.php(401): Mageplaza\\Seo\\Plugin\\SeoRender->addProductStructuredDataByType('configurable', Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#2 /home/user/public_html/app/code/Mageplaza/Seo/Plugin/SeoRender.php(245): Mageplaza\\Seo\\Plugin\\SeoRender->showProductStructuredData()\n#3 /home/user/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Mageplaza\\Seo\\Plugin\\SeoRender->afterRenderHeadContent(Object(Magento\\Framework\\View\\Page\\Config\\Renderer\\Interceptor), '<meta charset="...')\n#4 /home/user/public_html/ven...'

Regards,

**Comment by zapateroremendon** [comment]
Hello @giaphn 
I have made some modification between lines 736-740 in SeoRender.php module version 4.1.0 it seems to be working ok, what are your thought?
[SeoRender.zip](https://github.com/mageplaza/magento-2-seo/files/6429861/SeoRender.zip)

Thanks for your help !

**Comment by giaphn** [comment]
Great to hear that you fixed the issue yourself. It totally impressed me a lot.
Besides, I've passed that feedback along to our development team to suggest making it more readily available in the future if possible.

Once again, thank you very much for your valuable feedback and significant contribution.
If you have any further questions/issues, please feel welcome to reach back out as we would be more than happy to assist. 

I wish you a great day!

**Comment by giaphn** [comment]
Closed due no response within 7 days.
