### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by dragonfly4** [mageplaza/magento-2-seo#126]
### Magento v2.4.4 comes with PHP 8.1 support

There might be more issues. We have an Ultimate Pro license and the last update is from February 2022. When can we expect official support for PHP 8.1 please?

### Preconditions

1. Magento v2.4.4
2. PHP 8.1.6

### Steps to reproduce
1. Try to visit a product page with SEO url
2. 404 appears

### Expected result

1. Show product

### Actual result
1)
`main.CRITICAL: Exception: Deprecated Functionality: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /app/code/Mageplaza/SeoPro/module-seo-rule/Helper/Data.php on line 815 in /vendor/magento/framework/App/ErrorHandler.php:61`

Addedd ?? ''
`return str_replace('((category_name))', $categoryName, $meta ?? '');`

2) /app/code/Mageplaza/SeoPro/module-seo-pro/Helper/Data.php
function getDisableCanonicalPages
add ) ?? ''

**Comment by phutx** [comment]
Hello @dragonfly4,

I'm Onesh from Mageplaza.
Thanks for your interest in our Seo module and for bringing this issue to us. Feedback like this helps us constantly improve this extension and customer experiences by knowing what we are doing right and what we can work on. So, I appreciate you taking the time to send us this helpful response.
We are working to complete support with PHP 8.1 and will release a new version soon.
Once again, thanks for your significant contribution here. Our gratitude knows no bounds.
