### ISSUE TITLE
Image isn't displayed - Schema sees it as a 404 page

### ISSUE THREAD

**Issue by themew** [mageplaza/magento-2-seo#134]
### Preconditions (*)

1.Magento 2.4.5-p1
2.

### Steps to reproduce (*)

1. Install Magento-2-seo version 4.2.1
2. Check SEO schema result
3. Image displays 404 page
4.  Path should be `/media/catalog/product` but the url is only `/product` so the url is broken

### Expected result (*)

1. Image of product should appear
2.

### Actual result (*)

1. Site's 404 page
2.

**Comment by KhietNguyen83** [comment]
Regarding this issue, please download the extension directly from our site https://www.mageplaza.com/magento-2-seo-extension/ along with the support package for further inspections and technical support. Thanks a lot!

**Comment by themew** [comment]
I'll grab a copy from the site and take a look at it, however I see the demo on your site also doesn't work correctly.

Using the standard demo on your site, and going to product [](https://seo-demo.mageplaza.com/breathe-easy-tank.html)

Checking line 39 `"image": "https:\/\/seo-demo.mageplaza.com\/pub\/media\/catalog\/product\/w\/t\/wt09-white_main_1.jpg",` the link is broken and goes to a 404 page.

**Comment by themew** [comment]
Thanks for the update.  Unfortunately the Google Drive file didn't work.

The file located in `/vendor/mageplaza/magento-2-seo-extension/Plugin` worked by replacing the line with:
`'image'       => $this->getUrl('media/catalog') . 'product' . $currentProduct->getImage(),`
