### ISSUE TITLE
Exception when Magento_Inventory modules are disabled

### ISSUE THREAD

**Issue by duxabilii** [mageplaza/magento-2-seo#135]
### Preconditions (*)

1.  Magento ver. 2.4.2

### Steps to reproduce (*)

1. Disable Multi Source Inventory 
`php bin/magento module:disable -f Magento_Inventory Magento_InventoryAdminUi Magento_InventoryApi Magento_InventoryBundleProduct Magento_InventoryBundleProductAdminUi Magento_InventoryCatalog Magento_InventorySales Magento_InventoryCatalogAdminUi Magento_InventoryCatalogApi Magento_InventoryCatalogSearch Magento_InventoryConfigurableProduct Magento_InventoryConfigurableProductAdminUi Magento_InventoryConfigurableProductIndexer Magento_InventoryConfiguration Magento_InventoryConfigurationApi Magento_InventoryGroupedProduct Magento_InventoryGroupedProductAdminUi Magento_InventoryGroupedProductIndexer Magento_InventoryImportExport Magento_InventoryIndexer Magento_InventoryLowQuantityNotification Magento_InventoryLowQuantityNotificationAdminUi Magento_InventoryLowQuantityNotificationApi Magento_InventoryMultiDimensionalIndexerApi Magento_InventoryProductAlert Magento_InventoryReservations Magento_InventoryReservationsApi Magento_InventoryCache Magento_InventorySalesAdminUi Magento_InventorySalesApi Magento_InventorySalesFrontendUi Magento_InventoryShipping Magento_InventorySourceDeductionApi Magento_InventorySourceSelection Magento_InventorySourceSelectionApi Magento_InventoryShippingAdminUi Magento_InventoryDistanceBasedSourceSelectionAdminUi Magento_InventoryDistanceBasedSourceSelectionApi Magento_InventoryElasticsearch Magento_InventoryExportStockApi Magento_InventoryReservationCli Magento_InventoryExportStock Magento_CatalogInventoryGraphQl Magento_InventorySetupFixtureGenerator Magento_InventoryAdvancedCheckout Magento_InventoryDistanceBasedSourceSelection Magento_InventoryRequisitionList Magento_InventoryGraphQl Magento_InventoryBundleImportExport Magento_InventoryBundleProductIndexer Magento_InventoryInStorePickupApi Magento_InventoryInStorePickupAdminUi Magento_InventoryInStorePickup Magento_InventoryInStorePickupGraphQl Magento_InventoryInStorePickupShippingApi Magento_InventoryInStorePickupQuoteGraphQl Magento_InventoryInStorePickupSales Magento_InventoryInStorePickupSalesApi Magento_InventoryInStorePickupQuote Magento_InventoryInStorePickupShipping Magento_InventoryInStorePickupShippingAdminUi Magento_InventoryInStorePickupFrontend Magento_InventoryInStorePickupMultishipping Magento_InventoryInStorePickupSalesAdminUi Magento_InventoryInStorePickupWebapiExtension`
3. Install extension
4. Open any frontend page

### Expected result (*)

1. Site loaded as usually.

### Actual result (*)

1. Exception appear
`Error: Cannot instantiate interface Magento\InventoryApi\Api\GetSourceItemsBySkuInterface in /work/www/magento.localhost/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /work/www/magento.localhost/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#1 /work/www/magento.localhost/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#2 /work/www/magento.localhost/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#3 /work/www/magento.localhost/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#4 /work/www/magento.localhost/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#5 /work/www/magento.localhost/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#6 /work/www/magento.localhost/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#7 /work/www/magento.localhost/vendor/magento/framework/Interception/PluginList/PluginList.php(174): Magento\Framework\ObjectManager\ObjectManager->get()
#8 /work/www/magento.localhost/vendor/magento/framework/Interception/Interceptor.php(119): Magento\Framework\Interception\PluginList\PluginList->getPlugin()
#9 /work/www/magento.localhost/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Page\Config\Renderer\Interceptor->Magento\Framework\Interception\{closure}()
#10 /work/www/magento.localhost/generated/code/Magento/Framework/View/Page/Config/Renderer/Interceptor.php(50): Magento\Framework\View\Page\Config\Renderer\Interceptor->___callPlugins()
#11 /work/www/magento.localhost/vendor/magento/framework/View/Page/Config/Renderer.php(134): Magento\Framework\View\Page\Config\Renderer\Interceptor->renderMetadata()
#12 /work/www/magento.localhost/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#13 /work/www/magento.localhost/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Page\Config\Renderer\Interceptor->___callParent()
#14 /work/www/magento.localhost/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Page\Config\Renderer\Interceptor->Magento\Framework\Interception\{closure}()
#15 /work/www/magento.localhost/generated/code/Magento/Framework/View/Page/Config/Renderer/Interceptor.php(32): Magento\Framework\View\Page\Config\Renderer\Interceptor->___callPlugins()
#16 /work/www/magento.localhost/vendor/magento/framework/View/Result/Page.php(250): Magento\Framework\View\Page\Config\Renderer\Interceptor->renderHeadContent()
#17 /work/www/magento.localhost/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#18 /work/www/magento.localhost/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#19 /work/www/magento.localhost/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#20 /work/www/magento.localhost/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#21 /work/www/magento.localhost/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(95): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#22 /work/www/magento.localhost/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#23 /work/www/magento.localhost/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#24 /work/www/magento.localhost/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch()
#25 /work/www/magento.localhost/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#26 {main}`
![image](https://user-images.githubusercontent.com/966145/211857167-991a829e-8d98-4c60-ade3-e8924b8a300b.png)

Multi Source Inventory dependencies were found in `vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php`

**Comment by duxabilii** [comment]
Quick solution:
downgrade to version 4.2.0

**Comment by KhietNguyen83** [comment]
Thank you for your interest in the Mageplaza module.
If you disable the Magento_Inventory, please load and replace the file:
- https://github.com/mageplaza/magento-2-seo/blob/v4.2.0/Plugin/SeoRender.php
- Plugin/SeoRender.php

Thank you!

**Comment by duxabilii** [comment]
@KhietNguyen83
Thanks for the answer, but, as for me, replacing the file in the `vendor` folder is not a very correct solution.
