### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by afavata** [mageplaza/magento-2-seo#18]
Magento 2.1.5 with the latest Magento-2-seo downloaded from github

After filled all the information requested in backend pannel including twitter,
twitter meta tags are missed in the final HTML source page as follow: 

   meta name="twitter:card"
   meta name="twitter:site" 
   meta name="twitter:title"
   meta name="twitter:description"

**Comment by imsamthomas** [comment]
Hi,

We will look into this and update you soon.

Regards,
Support team

**Comment by afavata** [comment]
Hi @imsamthomas 
Just installed new version 1.2.0. It works like a charm
You can close this issue
Thanks indeed

Alex
