### ISSUE TITLE
Sitemap link not working

### ISSUE THREAD

**Issue by Tonop** [mageplaza/magento-2-seo#24]
### Preconditions

1. Magento: 2.1.6
2. PHP: 5.6.26
3. MySQL: 14.14 Distrib 5.7.15
4. 

### Steps to reproduce

1. User click on sitemap link
2. 
3. 

### Expected result

1. System generates sitemap

### Actual result

1. Error

1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with id = 3
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with id = 3
#0 /.../magento2/vendor/magento/module-catalog/Model/CategoryRepository.php(141): Magento\Framework\Exception\NoSuchEntityException::singleField('id', '3')

**Comment by imsamthomas** [comment]
We have tested on SEO v1.3.0 there is no issue.
Download it at https://github.com/mageplaza/magento-2-seo/releases/tag/v1.3.0
Or pull latest package https://github.com/mageplaza/magento-2-seo/

**Comment by Tonop** [comment]
Still the same error:

1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with id = 3

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with id = 3
#0 .../magento2/vendor/magento/module-catalog/Model/CategoryRepository.php(141): Magento\Framework\Exception\NoSuchEntityException::singleField('id', '3')
#1 .../magento2/app/code/Mageplaza/Seo/Block/Sitemap.php(137): Magento\Catalog\Model\CategoryRepository->get('3')
#2 .../magento2/app/code/Mageplaza/Seo/view/frontend/templates/sitemap/category.phtml(7): Mageplaza\Seo\Block\Sitemap->getCategoryUrl(Object(Magento\Catalog\Model\Category\Interceptor))
#3 .../magento2/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/swinestud...')
#4 .../magento2/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Mageplaza\Seo\Block\Sitemap), '/home/swinestud...', Array)
#5
...
#70 {main}

**Comment by TruongUET** [comment]
Hi all,

This issues has been fixed, please Clone the latest version to your site

Best Regards,
Truong Can!

**Comment by Tonop** [comment]
Now it works. Thank you!
