### ISSUE TITLE
Catalog Search Page Is Indexable By Search Engines

### ISSUE THREAD

**Issue by webspeaks** [mageplaza/magento-2-seo#25]
### Preconditions

1. Magento: 2.1.6
2. PHP: 7.0
3. MySQL: 5.6

### Steps to reproduce

1. Install MagePlaze SEO
2. In config, set "Add Nofollow meta in Search Result" to "Yes"
3. Check on catalog search page in frontend

### Expected result

1. You should see `<meta name="robots" content="NOINDEX,NOFOLLOW"/>` in source code

### Actual result

1. We get `<meta name="robots" content="INDEX,FOLLOW"/>` in source code
2. Canonical tag also seems to be wrong, it is `<link rel="canonical" href="https://domain.com/catalogsearch/result/?q=ceramic"/>`

Please let us know if it is a bug or intentional feature. As far as I know search pages should have NOFOLLOW meta tag to avoid indexing.

**Comment by imsamthomas** [comment]
Hi,

Our team is working on this and update you soon.

**Comment by TruongUET** [comment]
Hi all,

This issues has been fixed, please Clone the latest version to your site

Best Regards,
Truong Can!
