### ISSUE TITLE
error in php file

### ISSUE THREAD

**Issue by Frits1980** [mageplaza/magento-2-seo#29]
When I install via composer on magento 2.1.6 I get this error:

Parse error: syntax error, unexpected end of file in /data/web/magento/var/view_preprocessed/html/vendor/mageplaza/magento-2-seo-extension/view/frontend/templates/opengraph/category.phtml on line 1

**Comment by psapoznik** [comment]
Same error with version 2.1.5

**Comment by haitv282** [comment]
Hi there,

The issue has been fixed in the latest version 2.0.0. Please upgrade the extension and test again.
Thank you very much.
