### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function getSize() on null

### ISSUE THREAD

**Issue by psapoznik** [mageplaza/magento-2-seo#30]
PHP Fatal error:  Uncaught Error: Call to a member function getSize() on null in /home/web/public_html/vendor/magento/module-theme/Block/Html/Pager.php:299
Stack trace:
#0 /home/web/public_html/vendor/mageplaza/magento-2-seo-extension/Block/Navigation/Category.php(25): Magento\Theme\Block\Html\Pager->getTotalNum()
#1 /home/web/public_html/var/view_preprocessed/html/vendor/mageplaza/magento-2-seo-extension/view/frontend/templates/navigation/nextprev.phtml(1): Mageplaza\Seo\Block\Navigation\Category->getNextPageUrl()
#2 /home/web/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/web/p...')
#3 /home/web/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Mageplaza\Seo\Block\Navigation\Category), '/home/web/p...', Array)
#4 /home/web/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/luzdeco/p...')
#5 /home/web/pu in /home/luzdeco/public_html/vendor/magento/module-theme/Block/Html/Pager.php on line

**Comment by wc-matteo** [comment]
I have a similar issue:

```
Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function toHtml() on boolean in /var/www/vhosts/gioannashop.com/httpdocs/vendor/mageplaza/magento-2-seo-extension/Observer/Markup.php:23\nStack trace:\n#0 /var/www/vhosts/gioannashop.com/httpdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Mageplaza\\Seo\\Observer\\Markup->execute(Object(Magento\\Framework\\Event\\Observer))\n#1 /var/www/vhosts/gioannashop.com/httpdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(Mageplaza\\Seo\\Observer\\Markup), Object(Magento\\Framework\\Event\\Observer))\n#2 /var/www/vhosts/gioannashop.com/httpdocs/vendor/magento/framework/Event/Manager.php(66): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))\n#3 /var/www/vhosts/gioannashop.com/httpdocs/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\\Framework\\Event\\Manager->dispatch('layout_generate...\n', referer: https://www.gioannashop.com/gonne
```

**Comment by ausl** [comment]
Solved this by set Enable Next/Prev tag to 'No'

**Comment by TruongUET** [comment]
Hi all,

This issues has been fixed, please Clone the latest version to your site

Best Regards,
Truong Can!
