### ISSUE TITLE
Fatal Error: Call to a member function toHtml() on boolean in Observer/Markup.php:23

### ISSUE THREAD

**Issue by mkastaneda** [mageplaza/magento-2-seo#31]
### Preconditions

1. Magento: 2.1.6
2. PHP: 7.0.8
3. MySQL: Percona

### Steps to reproduce

1. Add Item To cart
2. Magento will make an ajax call to /customer/section/load/?sections=cart
3. Response is unable to be rendered because a fatal error is thrown
4. Mini Cart does not get refresh due to this error

### Expected result

1. Cart updated

### Actual result

1. Fatal error: Uncaught Error: Call to a member function toHtml() on boolean in vendor/mageplaza/magento-2-seo-extension/Observer/Markup.php:23 

### Suggested fix
1. Validate that Block exists before calling toHtml, or change the way you get the Block from layout on your method getBlock line 110

**Comment by afavata** [comment]
same issue  happen to me .... I had to disable the module

**Comment by imsamthomas** [comment]
Hi,
I have noted this issue internally and fix this soon.

**Comment by mkastaneda** [comment]
Thanks ! I had to manually apply the fix on a soon-to-go-live environment. Cant leave it there for much longer for obvious reasons. Any estimate on the release date with the official fix ?
