### ISSUE TITLE
Unexpected end of file causes catalog pages to crash when HTML Minification is enabled

### ISSUE THREAD

**Issue by mkastaneda** [mageplaza/magento-2-seo#33]
### Preconditions

1. Magento: 2.1.6
2. PHP: 7.0.8

### Steps to reproduce

1. Enable "Minify HTML" Option under Advanced -> Developer -> Template Settings 
2. Deploy static files
3. Go to a Category page

### Expected result

1. Render category properly

### Actual result

1. Page crashes withfatal error: Unexpected end of file in var/view_preprocessed/html/vendor/mageplaza/magento-2-seo-extension/view/frontend/templates/opengraph/category.phtml on line 1

### Solution
1. Remove PHP opening tag at the end of view/frontend/templates/opengraph/category.phtml

**Comment by TruongUET** [comment]
Hi all,

This issues has been fixed, please Clone the latest version to your site

Best Regards,
Truong Can!
