### ISSUE TITLE
Creating a bundle product in Magento-2.1.4 , while saving a bundle product with single drop-down product option duplicates the same option after saving the product.

### ISSUE THREAD

**Issue by tony831993** [mageplaza/magento-2-seo#35]
Full description of the problem here .

https://github.com/magento/magento2/issues/9565

seeking for support ASAP

**Comment by TruongUET** [comment]
Hi all,

This issues has been fixed, please Clone the latest version to your site

Best Regards,
Truong Can!

**Comment by magentocj** [comment]
Hi Truong Can
Could you please tell me what changes you have done for fix the duplicate issue of bundle 
I want to push only these changes so I am asking 
Thanks

**Comment by TruongUET** [comment]
Hi magentocj
I have
Edited:
Seo\etc\adminhtml\event.xml

**Comment by magentocj** [comment]
Hi 
After enable Mageplaza_Seo then we got this below issue , Could you please check it and update 
1 exception(s):
Exception #0 (OutOfRangeException): Specified invalid parent id (Mageplaza_Core::menu)

**Comment by TruongUET** [comment]
Hi,

We checked but did not see the error like you did, you try to check the Mageplaza Core extenstion by clone it from here.

Let us know the results

Best Regards,
Truong Can!

**Comment by magentocj** [comment]
Hi Truong Can
Could you please provide exact code for fixing the bundle issue in the below files 
Seo\etc\adminhtml\event.xml
Seo\Observer\Product.php
Currently, we are using  this version 1.1.3 for seo extension

**Comment by TruongUET** [comment]
Hi,
   Our purpose in the Product.php file is to set the value for the product url key
   In the default Magento, the bundle item is stored independently of the bundle product, while saving the bundle product, the bundle item is also saved, but in the old version. We called one more save bundle product + 1 save earlier, so the bundle item will be called multiple times leading to the duplicate bundle item.

In this version, we removed the save method.

Best Regards,
Truong Can

**Comment by magentocj** [comment]
Hi Truong Can

So you have removed this below code from event.xml file 
Path  app/code/Mageplaza/Seo/etc/adminhtml/events.xml
Our Magento version is : 2.1.7

**Comment by magentocj** [comment]
Hi 
Could you please tell me what I need to change for fix this issue with this veriosn :1.1.3

 Our Magento version is : Our Magento version is : 2.1.7

**Comment by TruongUET** [comment]
Hi,

Yes, we want to set value for url key before saving the product, but when we save the product in admin, default Magento just dispatch AFTER SAVE event, so we must change event for it.

Best Regards,
Truong Can!

**Comment by TruongUET** [comment]
Hi,

It is difficult to fix it remotely because we have tested it successfully.
If possible, provide us with your site's SSH information, we will help you fix it.

Best Regards,
Truong Can!

**Comment by magentocj** [comment]
Hi Truong Can!
Thanks for the update

1. We need to change event from controller_action_catalog_product_save_entity_after to  catalog_product_save_before  in the event.xml 

2 .Are we need to do any changes in product.php file ?

**Comment by TruongUET** [comment]
Hi,

We only not to call 'SAVE product' method 2 times

Best Regards,
Truong Can!
