### ISSUE TITLE
Invalid template file errors in var/log/system.log

### ISSUE THREAD

**Issue by dhob68** [mageplaza/magento-2-seo#42]
I am getting the following error message in var/log/system.log

> main.CRITICAL: Invalid template file: 'Mageplaza_Seo::richsnippets/jsonld/breadcrumb.phtml ' in module: 'Magento_Theme' block's name: 'breadcrumbs' [] []

I'm not noticing any problems other than having more than 28 thousand of these messages in the log.

### Preconditions

Magento: 2.1.7
PHP: 7.0.12
MySQL: Ver 15.1 Distrib 10.0.27-MariaDB
Varnish 4.1.3
Redis 3.2.3

**Comment by imsamthomas** [comment]
Hi @dhob68 ,

This issue has been fixed before, please download latest version at https://github.com/mageplaza/magento-2-seo or https://www.mageplaza.com/magento-2-seo-extension/
