### ISSUE TITLE
Blank Category Page after installation

### ISSUE THREAD

**Issue by Shopo** [mageplaza/magento-2-seo#55]
After installing Mageplaza SEO Extension, Category pages are blank on frontend on my website. How can I solve this problem in Magento 2.1.7. After installation of Mageplaza SEO, Magento Admin showing only this option in Settings. But In User Guide there are 3 option for SEO settings, but in our case, it is showing only one option. How can I solve this problem?
![seoissue](https://user-images.githubusercontent.com/33248912/32262035-527a05c4-bef8-11e7-817f-f11464567ef6.PNG)

**Comment by haitv282** [comment]
Hi there,

The problem has been solved on our latest version 2.0.1. Please upgrade the extension and check it again.
Thank you very much.
