### ISSUE TITLE
System log error: 'mageplaza_seo_breadcrumbs' element cannot be added as child to 'page.breadcrumbs', because the latter doesn't exist

### ISSUE THREAD

**Issue by Tonop** [mageplaza/magento-2-seo#57]
### Preconditions

1. Magento: 2.1.9
2. PHP: PHP 5.6.32 (cli) (built: Oct 25 2017 07:00:59)
3. MySQL: Ver 14.14 Distrib 5.7.15, for Linux (x86_64) using  EditLine wrapper
4. 

### Steps to reproduce

1. tail -f system.log
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]
[...]# tail -f system.log
[2017-12-20 06:00:25] main.INFO: Broken reference: the 'mageplaza_seo_breadcrumbs' element cannot be added as child to 'page.breadcrumbs', because the latter doesn't exist [] []

**Comment by imsamthomas** [comment]
This feature has been removed from Standard package.
