### ISSUE TITLE
Some products not getting structured data

### ISSUE THREAD

**Issue by jeffmalterre** [mageplaza/magento-2-seo#59]
### Preconditions

1. Magento: 2.2.2
2. PHP: 7.0
3. MySQL: 5.7
4. 

### Steps to reproduce

1. Install Magento
2. Install Module
3. 

### Expected result

1. Structured data should be on every product page

### Actual result

1. [Screenshot, logs]
I noticed a product that isn't getting structured data.  As far as I know it's the only one.

Product with structured data:
https://www.cfspharmacy.pharmacy/naltrexone-low-dose

Product without structured data:
https://www.cfspharmacy.pharmacy/pimobendan-tablets-compounded

**Comment by imsamthomas** [comment]
@Kenny1994 You should check **Configurable product** and make sure it works correctly

**Comment by haitv282** [comment]
This error has been solved in the latest version.
