### ISSUE TITLE
Open Graph tags not generated in "Pages"

### ISSUE THREAD

**Issue by antwake** [mageplaza/magento-2-seo#60]
### Preconditions
1. Magento: 2.1.6
2. PHP: 7
3. MySQL: 10.0.30-MariaDB

### Steps to reproduce
1. Create a new Page (Content / Elements / Pages / New Page
2. Go to page
3. Display source code

### Expected result
1. Should display all <og:> tags (ex: https://www.bicyclesquilicot.com/fr/velos/route/performance/cervelo-s3-ultegra-di2-6870)

### Actual result
1. Displays only _Open Graph Protocol for Facebook by Mageplaza SEO_ (ex: https://www.bicyclesquilicot.com/velo-club-quilicot-2018/)

In a product page, I can see the <og:> tags correctly generated.

Does this plugin doesn't generate OG tags in CMS pages or is it a bug?

thanks!

**Comment by bdtrung** [comment]
Hi, 
Currently, our Seo module does not support this feature on CMS pages.
I'm sorry about this inconvenience.

**Comment by antwake** [comment]
cleaning up old bug bruh?

**Comment by bdtrung** [comment]
I'm so sorry about this.
Next time, if you have any problem, feel free to contact us via [freshdesk](https://mageplaza.freshdesk.com/).
We will able to support you faster.

Thanks!
