### ISSUE TITLE
Duplicate rich snippet in Product pages

### ISSUE THREAD

**Issue by AgentGod** [mageplaza/magento-2-seo#63]
Hi
After installing the module and open product page in Google rich snippet testing tool, there are two product snippets. One seems to be generated by the module and the other one generated by Magento itself.
Does it creates any SEO problems?

**Comment by Zyles** [comment]
Same issue here. You need to disable the default rich snippets.

**Comment by ninhkx** [comment]
Hi there,
I am Jordi from Mageplaza support team.
This module constructs data according to Json-ld structure (default Magento is micro-data). Google will prioritize data json.
There is no conflict between the 2 data and you are completely assured of this.
If you have the further question, please let us know.

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
