### ISSUE TITLE
When the module is uninstalled, it doesn't remove the eav_attributes

### ISSUE THREAD

**Issue by joaoasrosa** [mageplaza/magento-2-seo#64]
When the module is uninstalled using `bin/magento module:uninstall Mageplaza_Seo --remove-data --clear-static-content` command, the `eav_attributes` related to the module are not cleaned.

### Preconditions
1. Magento: 2.2.3
2. PHP: 7.0.29
3. MySQL: Aurora MySQL 5.6.10a

### Steps to reproduce
1. Have a Magento installation with products
2. Install the Mageplaza SEO via composer
3. Configure the Mageplaza SEO for the existent products
4. Uninstall the module using the command above (using the official guidelines)
5. Go to the admin page
6. Open Catalog > Products
7. Select a Product (previous configured in step 3)
8. Click in Product Details

### Expected result
1. Open the Product Details page

### Actual result
1. Magento error page with the error record number
2. Opening the file with the record number in `<magento installation>/var/reports` we have the error showing the model `\Mageplaza\Seo\Model\Source\Robots` couldn't be loaded
3. Opening the MySql database and querying the table `eav_attribute` we can verify that *at least* two records are connected to the model above

### Workaround
1. From the `eav_attribute` with the `source_model ` equal to  `\Mageplaza\Seo\Model\Source\Robots`, set it to `NULL` (`UPDATE eav_attribute SET source_model = NULL WHERE attribute_id = FAULTY_ID;`)

# **DISCLAIMER: DO IT AT YOUR OWN RISK. MY SOLUTION CAN BREAK YOUR INSTALLATION. IF YOU GO TO DO IT, TAKE THE NECESSARY BACKUPS!**

### Sugestion
As part of the uninstallation process, clean the `eav_attribute` table for the related module attributes.

**Comment by bdtrung** [comment]
Hi,
The problem you are facing is only on the old version.
Our module has been updated and that problem has been solved.
Thank you for your feedback.
