### ISSUE TITLE
Wrong image url in structured data

### ISSUE THREAD

**Issue by jcourtei** [mageplaza/magento-2-seo#65]
### Preconditions
1. Magento: 2.2.6
2. PHP: 7.1
3. MySQL: 5.7

### Steps to reproduce
1. On the Admin Panel, System > Settings > Configuration.
2. On the left panel, under General, select Web.
3. Open the URL Options section:
4. Choose Yes in the Add Store Code.
5. Click Save Config to complete.
6. When prompted, click on Cache Management link to flush the cache.
7. View source code of simple product page.

### Expected result
In JSON-LD structured data, image url should not contain the store code.

### Actual result
In JSON-LD structured data, image url contains the store code, so the url is not valid.

Also, according to Google structured data testing tool (https://search.google.com/structured-data/testing-tool), Google expects to find url property in Offer type.

**Comment by bdtrung** [comment]
Hi,
Regarding your problem, please try to upgrade to the latest version of the Seo module.

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
