### ISSUE TITLE
Image SEO

### ISSUE THREAD

**Issue by Zyles** [mageplaza/magento-2-seo#67]
A new feature that would be great would be renaming the uploaded images files to have the product name in it.

This will improve image searches in Google.

For example, we store all images with SKU code for easy importing. When uploaded the image URL looks like this:

`https://example.store/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/s/c/sku-c-159-01.jpg`

It would be much better if the `sku-c-159-01.jpg` would be rewritten on the frontend to something like `my-product-name.jpg`.

If conflicts are an issue we could append the product name instead: `sku-c-159-01-my-product-name.jpg`

This would increase rankings in Google image search.

**Comment by bdtrung** [comment]
Hi, 
Thanks for your contribution.
We will note and consider to update this function into the module in the future.
