### ISSUE TITLE
Seo check tool robots.txt does not exist

### ISSUE THREAD

**Issue by Flakoeh** [mageplaza/magento-2-seo#69]
Only a minor "bug", On magento 2, with the mageplaza SEO ultimate extension when you use the "Check on page" function which redirects to http://seo.mageplaza.com/ it says robots.txt does not exist on products/category urls

Example 1, with this url it says robots.txt does exist:

https://www.example.com

But when you check for example an product url, it says the robots.txt does not exist:

https://www.example.com/product1

Solution: It should always check for robots.txt on the root url no matter what url is submitted.

**Comment by bdtrung** [comment]
Thanks for your contribution.
We will check and update it soon.

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
