### ISSUE TITLE
Page Is Not Working for Out of Stock Products

### ISSUE THREAD

**Issue by ewallteam** [mageplaza/magento-2-seo#70]
### Preconditions
1. Magento: 2.2.7
2. PHP: 7.0.30

### Steps to reproduce

 Go to Out of Stock Product in Frontend

### Expected result

Page should display without any issues

### Actual result

http://prntscr.com/nlvcoa

**Comment by DrakeJack** [comment]
I'm Drake from Mageplaza and I'll assist you.
Please turn the display error mode on in app/boostrap.php, remove the '#' symbol in
`#ini_set('display_errors', 1);`
https://prnt.sc/nlvhfh

Then turn back and provide me the screenshot about the problem in your site.

**Comment by ewallteam** [comment]
@DrakeJack 

Like this I'll get

Fatal error: Uncaught Error: Call to a member function getValue() on boolean in vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php:566 Stack trace: #0 vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php(649): Mageplaza\Seo\Plugin\SeoRender->getConfigurableProductStructuredData(Object(Magento\Catalog\Model\Product\Interceptor), Array) #1 vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php(347): Mageplaza\Seo\Plugin\SeoRender->addProductStructuredDataByType('configurable', Object(Magento\Catalog\Model\Product\Interceptor), Array) #2 vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php(203): Mageplaza\Seo\Plugin\SeoRender->showProductStructuredData() #3 vendor/magento/framework/Interception/Interceptor.php(146): Mageplaza\Seo\Plugin\SeoRender->afterRenderHeadContent(Object(Magento\Framework\View\Page\Config\Renderer\Interceptor), '<meta c in vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php on line 566

**Comment by Yonn-Trimoreau** [comment]
This issue is happening on our end too. On a fresh Magento 2.3.2 install. And if we do a quick search on Google, we're not the only one ! https://www.google.fr/search?q=vendor%2Fmageplaza%2Fmagento-2-seo-extension%2FPlugin%2FSeoRender.php&oq=vendor%2Fmageplaza%2Fmagento-2-seo-extension%2FPlugin%2FSeoRender.php

**Comment by DrakeJack** [comment]
@Yonn-Trimoreau is right, the issue is the same as getFrontEnd() issue, please refer to the solution at
https://github.com/mageplaza/magento-2-seo/issues/77

**Comment by Yonn-Trimoreau** [comment]
Wouldn't it be nice to commit this and publish a new release if you already know the fix?

**Comment by DrakeJack** [comment]
Yes, I'll commit the change to the newest version after testing it.

**Comment by onepack** [comment]
Not fixed yet in the latest module release?
M2.3.3 / PHP7.2
[Sun Dec 15 07:49:32.266159 2019] [proxy_fcgi:error] [pid 24412:tid 139828339132160] [client 2a01:7c8:fffa:f1::1:60390] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getValue() on boolean in /home/domain.com/public_html/vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php:699\nStack trace:\n#0 /home/dh01prod/domains/dochorse.com/public_html/vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php(792): Mageplaza\\Seo\\Plugin\\SeoRender->getConfigurableProductStructuredData(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#1 /home/domain.com/public_html/vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php(401): Mageplaza\\Seo\\Plugin\\SeoRender->addProductStructuredDataByType('configurable', Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#2 /home/domain.com/public_html/vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php(245): Mageplaza\\Seo\\Plugin\\SeoRender->showProductStructuredData()\n#3 /home/domain.com/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Mag...\n'

**Comment by DrakeJack** [comment]
I've pushed the change to develop branch but didn't merge to the Master branch, we need to have some more change after merging the branch.
You guys can you the develop branch for solving the issue!
