### ISSUE TITLE
Category sitemap exclusion defaults to 'yes'

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-seo#71]
### Preconditions
1. Magento: 2.2.8
2. PHP: 7.1

### Steps to reproduce

1. Install module

### Expected result

1. Category sitemap exclusion should default to 'no'

### Actual result

1. Category sitemap exclusion defaults to 'yes'

The new EAV attribute mp_exclude_sitemap for categories is added to the eav table but the default value for categories is 'yes'. I consider this potentiallly fatal as this would mean those categories would be excluded from the sitemap creation. I know the value is not initially saved to the database but all you need to do is open a category for editing (do something else) and then save it. If you don't pay attention the category ends up being exluded.

The default should be 'no' as this is most likely the more common scenario.

**Comment by OvalMedia** [comment]
Holy c**p. The product value defaults to 'yes' as well. This module is a SEO killer.

**Comment by OvalMedia** [comment]
My bad, wrong module. I created a new issue [here](https://github.com/mageplaza/magento-2-google-xml-sitemap/issues/5).

**Comment by bdtrung** [comment]
Close due to report in wrong module.
