### ISSUE TITLE
Version 2.2.0 doesn't work with Magento 2.2.x

### ISSUE THREAD

**Issue by juhanihaapala** [mageplaza/magento-2-seo#73]
### Preconditions
1. Magento: version 2.2.x

### Steps to reproduce

1. Install latest Mageplaza seo version v2.2.0 to Magento 2.2.x
2. Go to admin to product edit view

### Expected result

1. Normal edit view

### Actual result

`PHP message: PHP Fatal error:  Uncaught Error: Undefined class constant 'PARAM_NAME' in vendor/mageplaza/magento-2-seo-extension/Block/Adminhtml/SeoChecker/CheckForm.php:153`

That is because `StoreManagerInterface::PARAM_NAME` is only available in Magento 2.3.x

**Comment by oviliz** [comment]
Same exact problem here... :(

**Comment by oviliz** [comment]
Same exact problem here... :(
Have you found a workaround @juhanihaapala ?

**Comment by oviliz** [comment]
Downgraded to 2.1.4 and I can now edit the products.

**Comment by DrakeJack** [comment]
About the issue in the Product page and Category page in Admin, please go to file:
 + app/code/Mageplaza/Seo/Block/Adminhtml/SeoChecker/CheckForm.php
or
 + vendor/mageplaza/magento-2-seo/Block/Adminhtml/SeoChecker/CheckForm.php

Then find function getLink() and change the URL variable in 2 case ('catalog_product_edit', 'catalog_category_edit'

```
       case 'catalog_product_edit':
                $urlModel = $this->productRepository->getById($id)->getUrlModel();
                $product = $this->productFactory->create()->load($id)->setStoreId($storeId);
                //$url = $urlModel->getUrl($product, ['_query' => [StoreManagerInterface::PARAM_NAME => $storeCode]]);
                $url = $urlModel->getUrl($product) . "?___store=" . $storeCode;
                break;
       case 'catalog_category_edit':
                $category = $this->categoryRepository->get($id, $storeId);
                // $url = $category->getUrl(['_query' => [StoreManagerInterface::PARAM_NAME => $storeCode]]);
                $url = $category->getUrl() . "?___store=" . $storeCode;
                break;
```
