### ISSUE TITLE
Version 2.2.0 causes product pages to crash by default on Magento 2.2.x

### ISSUE THREAD

**Issue by lewisje** [mageplaza/magento-2-seo#74]
### Preconditions
1. Magento: 2.2.9
2. PHP: 7.0.33
3. MySQL: 10.2.26-MariaDB

### Steps to reproduce

1. Have or install Magento 2.2.9, with at least one product.
2. Install or upgrade to version 2.2.0 of the Mageplaza SEO module.
3. Navigate to a product page.

### Expected result

1. The page loads.

### Actual result

1. The page throws an HTTP 500 error.

This is the error:

    Fatal error: Uncaught Error: Call to a member function getFrontend() on boolean in ~/public_html/vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php:377
    Stack trace: #0 ~/public_html/vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php(245): Mageplaza\Seo\Plugin\SeoRender->showProductStructuredData()
    #1 ~/public_html/magento/vendor/magento/framework/Interception/Interceptor.php(146): Mageplaza\Seo\Plugin\SeoRender->afterRenderHeadContent(Object(Magento\Framework\View\Page\Config\Renderer\Interceptor), '

The line in question is part of the `showProductStructuredData` function, and the line in question is the end of this variable assignment:

    $modelValue = $product->getResource()
        ->getAttribute($this->helperData->getRichsnippetsConfig('model_value'))
        ->getFrontend()->getValue($product);

The problem arises because by default, the possibilities for the `model_value` configuration parameter do not exist, so the call to `getAttribute` returns `false` rather than an attribute; disabling Product Structured Data fixes this problem.

**Comment by bdtrung** [comment]
Hi @lewisje,
Regarding your problem, please refer to this #78.

**Comment by OvalMedia** [comment]
Why is this still in the stable branch???
