### ISSUE TITLE
Missing offerCount field for configurable products

### ISSUE THREAD

**Issue by richardwebdezign** [mageplaza/magento-2-seo#75]
### Preconditions
1. Magento: 2.3.2
2. PHP: 7.1
3. MySQL: 15.1

### Steps to reproduce

1. Create configurable product with simple products

### Expected result

1. offerCount fields should be supplied

### Actual result

1. offerCount field is omitted

**Comment by DrakeJack** [comment]
Thanks for the information, we will update the offerCount in the next release.

**Comment by Asma-Hawari** [comment]
Hi Mageplaza , offerCount is not added yet ?

**Comment by ibrar099** [comment]
Hello Mageplaza,
the offerCount is still missing. If there is anyway i can add locally please update me.
Regards,
ibrar

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza.
We have fixed this and are in beta testing. This update will be updated in the new version of the extension.
Please wait until the next version is released.
Thank you for working with us!
