### ISSUE TITLE
Does not work with 2.3.1

### ISSUE THREAD

**Issue by Zyles** [mageplaza/magento-2-seo#77]
"mageplaza/magento-2-seo-extension": "^2.1"

### Preconditions
1. Magento: 2.3.1
2. PHP: 7.1
3. MySQL: 14.14

### Steps to reproduce
1. Install extension
2. Go to product page

### Expected result
1. No error

### Actual result

```FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getFrontend() on boolean in /home/httpd/demo/vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php:377
Stack trace:
#0 /home/httpd/demo/vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php(245): Mageplaza\Seo\Plugin\SeoRender->showProductStructuredData()
#1 /home/httpd/demo/vendor/magento/framework/Interception/Interceptor.php(146): Mageplaza\Seo\Plugin\SeoRender->afterRenderHeadContent(Object(Magento\Framework\View\Page\Config\Renderer\Interceptor), '<meta charset="...')
#2 /home/httpd/demo/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Page\Config\Renderer\Interceptor->Magento\Framework\Interception\{closure}()
#3 /home/httpd/demo/generated/code/Magento/Framework/View/Page/Config/Renderer/Interceptor.php(26): Magento\Framework\View\Page\Config\Renderer\Interceptor->___callPlugins('renderHeadConte...', Array, Ar" while reading response header from upstream```

**Comment by xpoback** [comment]
I can confirm it also does not work with Magento 2.3.3
```
Fatal error: Uncaught Error: Call to a member function getFrontend() on boolean in /home/oleh/Projects/magento2.3.3/src/vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php on line 377

**Comment by mjankiewicz** [comment]
@xpoback https://github.com/mageplaza/magento-2-seo/pull/78

**Comment by DrakeJack** [comment]
You can try to add the condition to fix that issue in the file vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php

Line 377, instead of calling Frontend()
 `$modelValue = $modelValue->getFrontend()->getValue($product);`
You should use 
```
if ($modelValue) {
       $modelValue = $modelValue->getFrontend()->getValue($product);
}
```

And the same in the line 434:
 ```
if ($brandValue) {
       $brandValue = $brandValue->getFrontend()->getValue($product);
}
```

**Comment by websecureNL** [comment]
Same problem here and the 'fix' doesn't work because I do not have 
`$modelValue = $modelValue->getFrontend()->getValue($product);` on line 377. My code looks like this:
`$modelValue = $product->getResource()
                    ->getAttribute($this->helperData->getRichsnippetsConfig('model_value'))
                    ->getFrontend()->getValue($product);
`

**Comment by maiChuong** [comment]
Same here: I'm working with Magento CE v2.1.11 right now.
From line 375 – 377, we have:
375 |                $modelValue      = $product->getResource()
376 |                   ->getAttribute($this->helperData->getRichsnippetsConfig('model_value'))
377 |                    ->getFrontend()->getValue($product);

And the error notification shows two (!) as follows:
( ! ) Fatal error: Uncaught Error: Call to a member function getFrontend() on boolean in /var/www/html/miahome.vn/vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php on line 377
( ! ) Error: Call to a member function getFrontend() on boolean in /var/www/html/miahome.vn/vendor/mageplaza/magento-2-seo-extension/Plugin/SeoRender.php on line 377

Look at the time of the last comment by websecureNL, I think this problem takes more time to resolve than it should be. Any help would be great ... for now I put this comment to report the problem also occurs in v2.1.11.
