### ISSUE TITLE
Version 2.2.0 brakes "category" and "product" editing in adminhtml

### ISSUE THREAD

**Issue by jtalel** [mageplaza/magento-2-seo#79]
### Preconditions
1. Magento: 2.2.8
2. PHP: 7.1.30
3. MySQL:  5.7.26-29-log - Percona Server (GPL), Release '19'

### Steps to reproduce

1.  Installed Mageplaza Magento 2 SEO through composer. (2.2.0)
2.  Enable and configure Magento 2 SEO extension in Admin Panel.
3. In Admin Panel go to Catalog -> Category OR Catalog -> Product and attempt to edit an product.

### Expected result

1.  I should be able to either see category grid 
2. I should be able to edit product.

### Actual result

1. When Trying to open Category grid following error occurred: 
`/var/www/html/magento2/vendor/mageplaza/magento-2-seo-extension/Block/Adminhtml/SeoChecker/CheckForm.php on line 157`
2. When trying to open/edit a product:
`/var/www/html/magento2/vendor/mageplaza/magento-2-seo-extension/Block/Adminhtml/SeoChecker/CheckForm.php on line 153`

Those errors appear in Magento 2 dev mode. In production mode it simply show a blank page and no errors in logs.

**Comment by DrakeJack** [comment]
Please go to the file
 /vendor/mageplaza/magento-2-seo-extension/Block/Adminhtml/SeoChecker/CheckForm.php
Then change in line 153 to:
 `$url = $urlModel->getUrl($product) . "?___store=" . $storeCode;`
And line 157 is the same:
`$url = $category->getUrl() . "?___store=" . $storeCode;`

**Comment by jtalel** [comment]
> Please go to the file
> /vendor/mageplaza/magento-2-seo-extension/Block/Adminhtml/SeoChecker/CheckForm.php
> Then change in line 153 to:
> `$url = $urlModel->getUrl($product) . "?___store=" . $storeCode;`
> And line 157 is the same:
> `$url = $category->getUrl() . "?___store=" . $storeCode;`

I changed line 153 from:
`$url = $urlModel->getUrl($product, ['_query' => [StoreManagerInterface::PARAM_NAME => $storeCode]]);`
to:
`$url = $urlModel->getUrl($product) . "?___store=" . $storeCode;`

And, line 157 from:
`$url = $category->getUrl(['_query' => [StoreManagerInterface::PARAM_NAME => $storeCode]]);`
to:
`$url = $category->getUrl() . "?___store=" . $storeCode;`

Issue is now solved. Thanks.

**Comment by DrakeJack** [comment]
@jtalel  Please make sure that you have cleared the cache.
If the issue stills appear, please note the error log so I can check and give the proper solution for you.
