### ISSUE TITLE
Activation does not work

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-seo#83]
### Preconditions
1. Magento: 2.2.9
2. PHP: 7.1
3. Module-Version: 2.1.4

### Steps to reproduce

1. Go to /admin/system_config/edit/section/seo/
2. Hit "Activate Now"
3. 

### Expected result

1. Module gets activated

### Actual result

1. The spinner appears briefly
2. Page unchanged, module not activated, "Save Config" button disabled

**Comment by bdtrung** [comment]
Regarding your problem, please update the Core module to the latest version.
You can download it at this [link](https://github.com/mageplaza/module-core).

**Comment by OvalMedia** [comment]
That did it. Thank you.
