### ISSUE TITLE
Please review the constant. It throwing an error. Magento ver 2.2.7

### ISSUE THREAD

**Issue by syedsaleem086** [mageplaza/magento-2-seo#84]
https://github.com/mageplaza/magento-2-seo/blob/acada51ac92ab85b31c3bc2366fc9419628937c7/Block/Adminhtml/SeoChecker/CheckForm.php#L153

**Comment by DrakeJack** [comment]
The line 153 should be changed to
` $url = $urlModel->getUrl($product) . "?___store=" . $storeCode;`
You should also change the line 157 to 
` $url = $category->getUrl() . "?___store=" . $storeCode;`

**Comment by OvalMedia** [comment]
Will this be fixed in the repo. This should be a hotfix pusehd immediately. I don't understand how you are leaving store breaking issues in the repository for such ling times.

**Comment by bdtrung** [comment]
In the current version, we are using the format of Magento 2.3.x so it's not working on 2.1.x and 2.2.x
We will check again and make it also compatible with all of the versions.
Thanks!

**Comment by OvalMedia** [comment]
More than a month old. A simple and working fix was proposed and still the supposedly stable branch of this module is still broken. Why don't you actually have a stable and working version in a stable branch? It really is annoying to work with as it keeps failing me using composer.
