### ISSUE TITLE
Rich snippets problems

### ISSUE THREAD

**Issue by Zyles** [mageplaza/magento-2-seo#85]
### Preconditions
Magento: 2.3.3

### Steps to reproduce

1. Install module
2. Active rich snippets
3. Let Google crawl site

### Expected result

No errors in Google Search Console.

### Actual result

After Google crawled our new site they are complaining about rich snippets.

The errors are:
```
Missing field "priceValidUntil"
Missing field "aggregateRating"
Missing field "review"
Missing field "description"
```

Can these be fixed?

**Comment by Tuvpt** [comment]
Thank you for your interest in our extension.
Consider your issue, fields like aggregateRating, review, description are always available. for priceValidUntil field, you can add it in config

**Comment by surelockrich** [comment]
@Tuvpt @Zyles 

It will be more help full if you guide us for how to setup up simple product and configurable products.

Regards,

surelock
