### ISSUE TITLE
Add subcategories to sitemap

### ISSUE THREAD

**Issue by Zyles** [mageplaza/magento-2-seo#86]
Only top level categories are shown on the HTML sitemap. Should include subcategories too, they also need indexing.

### Preconditions
1. Magento: 2.3.3
2. PHP:  7.2

### Steps to reproduce

1. Activate HTML sitemap
2. View sitemap
3. Can only see top level categories

### Expected result

1. All categories including sub categories should be on the sitemap

### Actual result

1. Only top level categories are rendered

**Comment by Tuvpt** [comment]
Thank you for your interest in our module.
Please disable the Exclude Sitemap function in category

**Comment by Zyles** [comment]
I see. Maybe a config where you can set default exclude "no". Instead of having to manually edit every single category.

**Comment by Tuvpt** [comment]
Thanks for your suggestions. We will consider it in the next updated version

**Comment by danilinked** [comment]
Hi @Tuvpt,
You already implement this option that @Zyles ask?
