### ISSUE TITLE
Ability to control META robots

### ISSUE THREAD

**Issue by Zyles** [mageplaza/magento-2-seo#88]
Would be great if it was possible to change the META robots field on pages. We do not want to index them all, but we can not change it to "noindex, follow" for example.

**Comment by Tuvpt** [comment]
Firstly, I truly apologize for the inconvenience.
Unfortunately, the current version has not supported this function yet. You need to use our upgrade to add this functionality

**Comment by Zyles** [comment]
What upgrade?

**Comment by Tuvpt** [comment]
Our SEO pro version has the features that you might be interested. Please refer this link
https://www.mageplaza.com/magento-2-seo-extension/
