### ISSUE TITLE
The store that was requested wasn't found due Mageplaza_SeoUrl

### ISSUE THREAD

**Issue by dragonfly4** [mageplaza/magento-2-seo#89]
Fatal error loading Homepage without specifying a store view code in the URL. This is due a problem with Mageplaza_SeoUrl. Disabling that module resolves the error.

`php bin/magento module:disable Mageplaza_SeoUrl`

### Preconditions
1. Magento: 2.3.4
2. PHP: 7.3.16
3. MySQL: 5.7

### Steps to reproduce
1. Install Mageplaza SEO Extension v2.2.1 (Ultimate version in our case)
2. Change setting "Add Store Code to Urls" to yes. [ Stores --> Settings --> Configuration --> General --> Web ]
3. Browse to your website without specifying a store view. Example: https://mysite.com/ vs https://mysite.com/en/

### Expected result
1. Homepage should load

### Actual result
1. Error: The store that was requested wasn't found. Verify the store and try again. Full error is attached.

[MageplazaSeoError.txt](https://github.com/mageplaza/magento-2-seo/files/4374314/MageplazaSeoError.txt)

**Comment by Shinichi69** [comment]
Hi @dragonfly4 

Regarding your issue, please follow the ticket you created.
I will check your problem and answer you on that ticket.

Thanks so much!

**Comment by dragonfly4** [comment]
@Shinichi69 I think I found the issue. The latest version of Seo Url dates from 2018.

/app/code/Mageplaza/SeoUrl/App/Request/StorePathInfoProcessor.php

L58 searches for a store code in the URL. That fails when it is not specified and causes the error.

` 
$pathParts = explode('/', ltrim($pathInfo, '/'), 2);
$storeCode = $pathParts[0];
`

**Comment by dragonfly4** [comment]
Issue has been confirmed as a bug and will be fixed in the next release.
