### ISSUE TITLE
product page can't show review stars

### ISSUE THREAD

**Issue by rackyan** [mageplaza/magento-2-seo#90]
### Preconditions
1. Magento:  2.3.4   Mageplaza seo 2.2.1
2. PHP:   7.2.11
3. MySQL:  5.7

### Steps to reproduce

1. Install module
2. Enable structurer data
3. Review rating stars replaced by Be the first to review this product, but the rating stars can display after disabled structurer data.

### Expected result

1.  Enable structurer data and review stars are vailable on product page as well.

**Comment by Bang512** [comment]
Hi @rackyan,

Thanks for contacting us.
I still can review starts on my local environments.

As you can see, here is my backend configuration:
![image](https://user-images.githubusercontent.com/49020344/79186196-2cef2480-7e43-11ea-8bdc-dbff2cd8afb4.png)

And I still can review starts:
![image](https://user-images.githubusercontent.com/49020344/79186220-4001f480-7e43-11ea-92f9-02a310eb73c5.png)

Please help me re-check.
Thank you!

**Comment by rackyan** [comment]
Hi @Bang512 

Thanks for your response.
My backend configuration is almost like yours, the rating stars in review block is valid, but it can't be shown below product name and it is replaced by "Be the first to review this product" link. If I disable structurer data, the review starts function is back to work. 

My settings 
![reviewrating-1](https://user-images.githubusercontent.com/28351786/79242162-89cff680-7ea6-11ea-9300-fbf8b2e763fa.png)
Can't show review stars 
![reviewrating-2](https://user-images.githubusercontent.com/28351786/79242173-8b99ba00-7ea6-11ea-9fb0-1a5ac4b893af.png)
Have two reviews for this product
![reviewrating-3](https://user-images.githubusercontent.com/28351786/79242170-8b012380-7ea6-11ea-9068-7613d8c14ac2.png)

Thanks

**Comment by cian-castillo** [comment]
This issue is also happening in our store

**Comment by bharatvimirlab** [comment]
Yes, the same issue after upgrading the Magento version 2.3.5

**Comment by AlexNauta** [comment]
I also have this issue, M2.3.5 / SEO 2.2.4

**Comment by ciancastillo** [comment]
Anyone found a solution for this? All those who installed this module will experience the same issue. How come the developers doesn't recognize this?
