### ISSUE TITLE
Configurable product gives error 500 due SEO plugin

### ISSUE THREAD

**Issue by dragonfly4** [mageplaza/magento-2-seo#91]
### Preconditions
1. Magento: 2.3.4
2. PHP: 7.3.16
3. MySQL: 5.7

### Steps to reproduce

1. Create a Configurable Product in Magento
2. Browse front-end

### Expected result

1. Show product Page

### Actual result

1. Error 500

> [13-Apr-2020 11:35:08 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getValue() on bool in /public_html/app/code/Mageplaza/Seo/Plugin/SeoRender.php:703
Stack trace:
#0 /public_html/app/code/Mageplaza/Seo/Plugin/SeoRender.php(796): Mageplaza\Seo\Plugin\SeoRender->getConfigurableProductStructuredData(Object(Magento\Catalog\Model\Product\Interceptor), Array)
#1 /public_html/app/code/Mageplaza/Seo/Plugin/SeoRender.php(401): Mageplaza\Seo\Plugin\SeoRender->addProductStructuredDataByType('configurable', Object(Magento\Catalog\Model\Product\Interceptor), Array)
#2 /public_html/app/code/Mageplaza/Seo/Plugin/SeoRender.php(245): Mageplaza\Seo\Plugin\SeoRender->showProductStructuredData()
#3 /public_html/vendor/magento/framework/Interception/Interceptor.php(146): Mageplaza\Seo\Plugin\SeoRender->afterRenderHeadContent(Object(Magento\Framework\View\Page\Config\Renderer\Interceptor), '<meta charset="...')
#4 /public_htm in /public_html/app/code/Mageplaza/Seo/Plugin/SeoRender.php on line 703

Line 703

`        $productStructuredData['offers']['highPrice'] = $currentProduct->getPriceInfo()->getPrice('regular_price')->getMaxRegularAmount()->getValue();`

A configurable Product has no price as that's defined by it's child products.

![image](https://user-images.githubusercontent.com/221351/79118156-53eb1f00-7d8d-11ea-8b8a-4a80b7608f65.png)

**Comment by Bang512** [comment]
Hi @dragonfly4,

Thanks for contacting us.
Can you show me the child product info of this configurable product?

I am looking forward to hearing from you.
Thank you!

**Comment by jasuten** [comment]
I get this error on configurable products where there are no children assigned to them yet.

**Comment by jalung** [comment]
It apparently happens on any product that is out of stock and Stores > Configuration > Catalog > Inventory > Display Out of Stock Products is set to No. Setting this to Yes avoids the bug and prevents the 500 server error.

**Comment by TTO-Owen** [comment]
Is there any progress to resolving this issue? We are also receiving the same error (Thanks to @jalung for highlighting a quick temporary fix)

**Comment by TTO-Owen** [comment]
Is there any progress to resolving this issue? We are also receiving the same error (Thanks to Jalung for highlighting a quick temporary fix)

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza.
To fix this problem, please help me download and replace this file:
- app/code/Mageplaza/Seo/Plugin/SeoRender.php
- https://www.dropbox.com/s/mig2ji1bc564bli/SeoRender.php?dl=0
Then clear the cache and check again.
Thank you!

**Comment by TTO-Owen** [comment]
> Hi, I'm Shox from Mageplaza. To fix this problem, please help me download and replace this file:
> 
> * app/code/Mageplaza/Seo/Plugin/SeoRender.php
> * https://www.dropbox.com/s/mig2ji1bc564bli/SeoRender.php?dl=0
>   Then clear the cache and check again.
>   Thank you!

With the added parameter on the construct for the SeoRender class, it fails to initiate.

```1 exception(s):
Exception #0 (Magento\Framework\Exception\RuntimeException): Type Error occurred when creating object: Mageplaza\Seo\Plugin\SeoRender, Too few arguments to function Mageplaza\Seo\Plugin\SeoRender::__construct(), 20 passed in /var/www/vhosts/staging.thetechout.com/httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121 and exactly 21 expected

Exception #0 (Magento\Framework\Exception\RuntimeException): Type Error occurred when creating object: Mageplaza\Seo\Plugin\SeoRender, Too few arguments to function Mageplaza\Seo\Plugin\SeoRender::__construct(), 20 passed in /var/www/vhosts/staging.thetechout.com/httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121 and exactly 21 expected
<pre>#1 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#2 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/Interception/PluginList/PluginList.php:174]
#3 Magento\Framework\Interception\PluginList\PluginList->getPlugin() called at [vendor/magento/framework/Interception/Interceptor.php:119]
#4 Magento\Framework\View\Page\Config\Renderer\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#5 Magento\Framework\View\Page\Config\Renderer\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Page/Config/Renderer/Interceptor.php:50]
#6 Magento\Framework\View\Page\Config\Renderer\Interceptor->renderMetadata() called at [vendor/magento/framework/View/Page/Config/Renderer.php:134]
#7 Magento\Framework\View\Page\Config\Renderer->renderHeadContent() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#8 Magento\Framework\View\Page\Config\Renderer\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#9 Magento\Framework\View\Page\Config\Renderer\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#10 Magento\Framework\View\Page\Config\Renderer\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Page/Config/Renderer/Interceptor.php:32]
#11 Magento\Framework\View\Page\Config\Renderer\Interceptor->renderHeadContent() called at [vendor/magento/framework/View/Result/Page.php:250]
#12 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#13 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#14 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#15 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#16 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:95]
#17 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#18 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#19 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#20 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
</pre>```

**Comment by giaphn** [comment]
Hi,
Please try install this version of SEO module and check again:
[Seo.zip](https://github.com/mageplaza/magento-2-seo/files/7801361/Seo.zip)

**Comment by TTO-Owen** [comment]
> Hi, Please try install this version of SEO module and check again: [Seo.zip](https://github.com/mageplaza/magento-2-seo/files/7801361/Seo.zip)

That version has resolved the issue and the update has corrected the initial issue, Please could you let me know what version of the module that zip is so I can update my composer file.

**Comment by giaphn** [comment]
At present, the version I sent to you is the fix. However, it is in the testing process and has not been released yet.
Please give us more time and be patient until this version is published. Your understanding means a lot to us. Thanks a bunch!

**Comment by giaphn** [comment]
Closed due to no responses in 7 days
