### ISSUE TITLE
Error for configurable products

### ISSUE THREAD

**Issue by pysebb** [mageplaza/magento-2-seo#93]
### Preconditions
1. Magento: 2.3.4
2. PHP: 7.1.33
3. MySQL:  14.14

### Steps to reproduce

1. Enable SEO extension
2. Some products have error in app/code/Mageplaza/Seo/Plugin/SeoRender.php on line 703

### Actual result
1. 
```
Fatal error: Uncaught Error: Call to a member function getValue() on boolean in /var/www/html/app/code/Mageplaza/Seo/Plugin/SeoRender.php:703 Stack trace: #0 /var/www/html/app/code/Mageplaza/Seo/Plugin/SeoRender.php(797): Mageplaza\Seo\Plugin\SeoRender->getConfigurableProductStructuredData(Object(Magento\Catalog\Model\Product\Interceptor), Array) #1 /var/www/html/app/code/Mageplaza/Seo/Plugin/SeoRender.php(403): Mageplaza\Seo\Plugin\SeoRender->addProductStructuredDataByType('configurable', Object(Magento\Catalog\Model\Product\Interceptor), Array) #2 /var/www/html/app/code/Mageplaza/Seo/Plugin/SeoRender.php(245): Mageplaza\Seo\Plugin\SeoRender->showProductStructuredData() #3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(146): Mageplaza\Seo\Plugin\SeoRender->afterRenderHeadContent(Object(Magento\Framework\View\Page\Config\Renderer\Interceptor), '<meta charset="...') #4 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Page\Config\Renderer\Interceptor->Mage in /var/www/html/app/code/Mageplaza/Seo/Plugin/SeoRender.php on line 703
```

**Comment by Bang512** [comment]
Hi @pysebb,

Thanks for contacting us.
However, I am not able to reproduce your problem on my local environment. Can you please send me some information on that product? 
Ex: type of product, child of the product (if have), ... and some screenshot.

It will help me can reproduce your problem on my local and find the reason and solution for this problem.

I am looking forward to hearing from you.
Thank you!

**Comment by pysebb** [comment]
This occurs whenever  a configurable product does not have any in stock children products.
