### ISSUE TITLE
Brand with an incorrect hardcoded default value

### ISSUE THREAD

**Issue by taskula** [mageplaza/magento-2-seo#98]
### Preconditions (*)

1. 2.3.5-p1
2. PHP 7.2

### Steps to reproduce (*)

1. Use Mageplaza SEO module
2. Enable product structured data from Stores -> Configuration -> Mageplaza Extensions -> SEO -> Structured Data
3. Have a product without the attribute that is chosen as the brand value in Mageplaza SEO
4. View your product in your store, open page source code

### Expected result (*)

1. Product property brand does not exist.

### Actual result (*)

1. Observe Product property "brand" with an incorrect value
```
"brand": {
        "@type": "Thing",
        "name": "Brand"
    }
```

See https://github.com/mageplaza/magento-2-seo/blob/eb669196f2d9fd7ec313dd1a45936f6f9b70b4b5/Plugin/SeoRender.php#L433-L440

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza.
By default, Magento doesn't have 'brand' attribute. So our SEO extension will check if you don't use our Shopbybrand module, it will get the data you set in the config: https://prnt.sc/ujc5q0 with type is 'thing'. I hope you understand that.

**Comment by taskula** [comment]
The issue is that brand is hardcoded as `Brand` if your other plugin is not in use and there is no product value for whatever attribute you have chosen as brand in the settings.

Instead of hardcoding "Brand" we should just completely remove the brand property of the Project JSON-MD altogether when no value is found.

**Comment by giaphn** [comment]
Thanks for your contribution. I will transfer your valuable comments to the relevant department to consider. Once again, thank you so much for your sharing and contribution. This will help us develop our product even more and provide customers with better services.

**Comment by giaphn** [comment]
Closed due no response within 7 days.
